providers = ["python"]
[phases.setup]
nixPkgs = ["...", "ffmpeg", "gcc"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "cd web/frontend && npm install"
]

[phases.build]
cmds = [
  "cd web/frontend && npm run build"
]

[start]
cmd = "python main.py"
